# Generated by Django 5.2.7 on 2025-10-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together=set(),
        ),
    ]
