# Generated by Django 5.2.7 on 2025-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_image_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('lift', 'Lift'), ('explore', 'Explore'), ('vault', 'Vault')], default='explore', max_length=20),
        ),
    ]
