# Generated by Django 5.2.7 on 2025-10-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
